language: python
python:
  - "3.6"

# command to install dependencies
install:
  - sudo apt install python3-rtree
  - pip install wheel
  - pip install -r requirements.txt

# command to run tests
script:
  - make test
